### ISSUE TITLE
Inference on Custom Class

### ISSUE THREAD

**Issue by barzamini** [rohit901/cooperative-foundational-models#6]
Thank you for your interesting project.

Could you please help us understand how we can test your code for novel classes that are not in LVIS or Coco? For example, I would like to test your method for a set of classes related to lane markers. Could you please provide any examples that I can follow, so that I can test your work for custom classes on any images?

Kind Regards

**Comment by rohit901** [comment]
Hello,

Thank you so much for your interest in our work. 

So let me tell you about our problem setting and give you some references in the code to help you with your task.

We consider COCO classes as "known" and LVIS classes as "novel".

First, we convert an existing closed-set detector (Mask-RCNN) which is trained on "known" classes only to an open-set detector which can generalize to "novel classes" using CLIP. These novel classes are specified here in code: 
https://github.com/rohit901/cooperative-foundational-models/blob/fb45630c46d75f7a1856654665191aeddeb3eb98/scripts/novel_object_detection/load_models.py#L36

You may have to change the above line for your use case, and also optionally use class synonym information for these classes if you have them available with you. 

Secondly, we also combine our "open-set Mask-RCNN" with existing SOTA open-set detector (i.e. Grounding DINO/GDINO) to get better performance. This GDINO model is not directly trained on COCO/"known" classes in our setting which is important to make open-vocab comparison on COCO fair. 

Thus, for your use case you may choose to remove the GDINO model, or use a different model trained on your custom "known" splits if you would like, or use the existing GDINO model as it is. You may have to experiment to see what works. 

Thus, I hope the above will help you to test the method on your custom classes. 
Can you try to once run the code on your machine by following the instructions in README, and then try to modify the novel classes accordingly? 

Let me know if you require any assistance.

**Comment by barzamini** [comment]
Thank you for the helpful insight. I could have made my change, but a new class needs to be added to lvis_classes or substituted with it wherever we have lvis_classes.
